# Generated by Django 6.0.2 on 2026-02-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                ("id_kategori", models.AutoField(primary_key=True, serialize=False)),
                ("nama_kategori", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id_status", models.AutoField(primary_key=True, serialize=False)),
                ("nama_status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Produk",
            fields=[
                ("id_produk", models.AutoField(primary_key=True, serialize=False)),
                ("nama_produk", models.CharField(max_length=50)),
                ("harga", models.DecimalField(decimal_places=2, max_digits=50)),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produk_app.kategori",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produk_app.status",
                    ),
                ),
            ],
        ),
    ]
